# Site
repository: elizav555.github.io/cv_eng
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Elizaveta Garkina
title: Android Developer
email: lizagarkina5@gmail.com
website: https://elizav555.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  Elizav555
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: __elizav__
linkedin_username: elizavg
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: telegram
  icon: fa fa-telegram
  url: https://t.me/ElizavG
# - title: vk
#   icon: fa fa-vk
#   url: https://vk.com/elizavetagarkina

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Hey, My name is **Elizaveta Garkina**, date of birth **01.09.2002**, at the moment I live in **Kazan**.

 Have been involved in mobile app development **since 2021**. Started out with **Flutter** development, but got into native development pretty quickly. I also have a little experience of creating websites using **Asp.Net Core** and recently I've started learning **ReactNative**.

 <mark>Desired position:</mark> **Middle Android Developer** 

  - Native language is Russian
  - English level is C1
  - Also know a little bit of French and Spanish

  - Sociable and easily join the team
  - Fast learner and inquisitive
  - Always meet deadlines and have the makings of a good leader
content:
  - title: Skills # Title for the section
    layout: text # Type of content section (list/text)
    # content: |
    #     <center>
    #        <mark>Compose</mark>  <mark>Room</mark>  <mark>Firebase</mark>  <mark>Dagger2</mark>  <mark>Hilt</mark>  <mark>ViewModel</mark>  <mark>LiveData</mark>  <mark>Flow</mark> <br><br> 
    #        <mark>Moxy</mark>  <mark>Cicerone</mark>  <mark>RxJava</mark>  <mark>Coroutines</mark>  <mark>Retrofit</mark>  <mark>Okhttp</mark>  <mark>JUnit5</mark>  <mark>Mockito</mark>  <br><br>
    #        <mark>SOLID</mark>  <mark>Clean Architecture</mark>  <mark>MVP</mark>  <mark>MVVM</mark> <mark>MVI</mark> <mark>VIPER</mark>  <br><br>
    #        <mark>SQL</mark>  <mark>PostgreSql</mark>  <mark>Figma</mark>  <mark>Git</mark>   <mark>JS</mark>  <mark>JQuery</mark>  <mark>HTML</mark>  <mark>CSS</mark><br><br>  
    #        <mark>ASP.Net Core</mark>  <mark>.Net6</mark>  <mark>EntityFramework Core </mark>
    #        </center>  
    content: |
        <center>
         <mark>Kotlin</mark>
         <mark>XML</mark> <mark>Compose</mark>
         <mark>Coroutines</mark> <mark>Flow</mark> <mark>LiveData</mark> <mark>RxJava</mark><br><br>
         <mark>SOLID</mark> <mark>CleanArchitecture</mark> <mark>MVP</mark> <mark>MVVM</mark> <mark>MVI</mark><br><br>
         <mark>NavigationComponent</mark> <mark>Cicerone</mark>
         <mark>Hilt</mark> <mark>Dagger2</mark>
         <mark>Retrofit</mark> <mark>Okhttp</mark><br><br>
         <mark>SharedPreferences</mark> <mark>Room</mark> <mark>Firebase</mark>
         <mark>JUnit5</mark> <mark>Mockito</mark> <mark>Charles</mark><br><br>
         <mark>KotlinSerialization</mark> <mark>Lottie</mark> <mark>Moshi</mark><br><br><mark>AdapterDelegates</mark> <mark>SlackEitherNet</mark> <mark>Paging3</mark> <mark>Moxy</mark> <mark>CameraX</mark> <mark>Camera2</mark><br><br>
         <mark>Flutter</mark> <mark>MachineLearning</mark> <mark>SystemAnalysis</mark> <mark>Scrum</mark> <mark>Kanban</mark><br><br>
         <mark>SQL</mark> <mark>PostgreSql</mark> <mark>Figma</mark> <mark>Git</mark> <mark>JS</mark> <mark>HTML</mark> <mark>CSS</mark>
         <br><br>
         <mark>Communicative</mark> <mark>Responsible</mark> <mark>Disciplined</mark> <mark>Leader</mark> <mark>Purposeful</mark>
        </center>
        

  - title: Experience 
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: T-Bank
        link: https://www.tbank.ru/
        link_text: tbank.ru
        sub_title: Android Developer
        caption: June 2024 - ...
        description: |
          <mark>Developer in the Fuel team.</mark>

      - layout: left
        title: Technokratos (Технократия)
        link: https://technokratos.com/?ysclid=l8g67dlhzr518675436
        link_text: technokratos.com
        sub_title: Android Developer
        caption: May 2023 - June 2024
        description: |
            <mark>Implementation of manufacturing process control system and production tooling storage, MES system.</mark><br>
            **Responsibilities:**
            - Lead of Android development team
            - Creating components for UiKit
            - Adaptation of the application for different devices: terminal, tablet, smartphones
            - Development and implementation of new features and refactoring of existing functionality
            - Realization of work with external camera and internal storage of the device
            - Code-review
            - Fixing bugs and solving technical problems
            - Application performance optimization
            - Covering code with unit tests

            **Stack:** Kotlin • XML • Kotlin Coroutines • Flow • MVVM • Navigation Component • Dagger Hilt • Retrofit2 • Okhttp3 • Chucker • Encrypted Shared Preferences • MediaStore • Datastore •  KotlinX Serialization • Lottie • Camera 2 •  Facebook Shimmer • ViewPager2 • AndroidX Paging • Coil • AndroidX Swipe Refresh Layout • FlexBox
            
            **During this time:**
            - Created a service for logging requests and errors within the application into json files
            - Worked with NFC sensor and external camera
            - Created a common mechanism for error handling in the whole application
            - Realized work with table views with fixing of headers and columns
            - Received **positive** feedback from the team and the customer throughout the job<br><br>   
          
            <mark>Auditing application code for an insurance company</mark><br>
            **During this time:**
            - Designed an audit plan and created a report template for mobile developers
            - Used MobSF, LeakCanary, Accessibility Scanner, SonarQube
            - Analyzed the project architecture<br><br><br>

      - layout: left
        title: Spider Group
        link: https://spider.ru/
        link_text: spider.ru
        sub_title: Android Developer
        caption: November 2022 - May 2023
        description: |
            <mark>Application development for an online lottery ticket purchase service.</mark><br>
            **Responsibilities:**
            - Lead Android Developer
            - Development of new features
            - Onboarding of other developers and further support
            - Large number of tasks with multithreading
            - Extensive code refactoring with the addition of new technologies
            - Architectural decision making
            - Code-review
            
            **Stack:** Kotlin • XML • Coroutines • Flow • MVVM • Cicerone • Dagger2 • Retrofit • Shared Preferences • Moshi • AdapterDelegates • Slack EitherNet • Paging 3
            
            **During this time:**
            - Engaged in creating loaded screens with complex ui. For example, lottery screens with the ability to set an unlimited number of tickets according to different lottery rules, notifications, buying and paying for tickets and their sets
            - Successfully onboarded three developers into the project and assisted them with designing new functionality
            - Implemented on-the-fly localization with multi-language support
            - Organized the camera and gallery and pre-processed photos before sending them to the server
            - Worked with converting images for different containers
      - layout: left
        title: Technokratos (Технократия)
        link: https://technokratos.com/?ysclid=l8g67dlhzr518675436
        link_text: technokratos.com
        sub_title: Summer Internship
        caption: July 2022
        description: | # this will include new lines to allow paragraphs
            During the internship I participated in the development of the company's internal project with **full immersion in the development process**. For the first time I worked with **Compose**.<br>
            *"In short, you are good, we are satisfied with your work. I want to note your motivation and involvement, your speed of immersion in new technologies and completing tasks, a clear breakdown of code by commit, good design of pull-requests, quick response to comments, the presence of your own ideas and suggestions. Also noted soft skills, the fact that you didn't hesitate to ask questions not only to mentors, but also to designers and analysts - that's very cool"* - @MyMentor

  - title: Education 
    layout: list 
    content:
      - layout: left
        title: Kazan Federal University
        caption: 2020 - 2024
        sub_title: Software Engineering, ITIS
        description: |
          **Diploma with honors**, grade point average : 4.9.<br>
          Theme of the thesis: **Methods and program mechanisms for generating visual models of Android application structure.**<br>
          Was attached to the **Mobile Development Laboratory** at the university.<br>
          As part of my undergraduate studies, I **gained a strong background knowledge in a variety of areas** including:<br> Discrete Mathematics, Mathematical Analysis, Algorithms and Data Structures, Probability Theory and Mathematical Statistics, Database Operations, Operating System Architecture, Software Development Lifecycle, Information and Coding Theory, Information Security, UI/UX Design, System Analytics, Fundamentals of System Testing, Web Development, Data Mining, Machine Learning.

      - layout: left
        title: Skillbox
        caption: 2020-2022
        sub_title: Flutter-developer
        description: | 
          Studied **Flutter, Android Basics, Figma, Mobile App Testing, Mobile App Design**.

      - layout: left
        title: Courses in Kazan Federal University
        caption: 2022 - 2023
        sub_title: System Analysis, UI/UX Design
        description: | 
          Successfully completed the courses of **System analysis from BARS Group and UI/UX design from Agona**.

  - title: Hobbies
    layout: text 
    content: |
        - Trying to lead an **active lifestyle**, insterested in **trying something new** and **participating in team activities**
        - I've loved reading since childhood, especially **dystopias and fiction**, lately I've been drawn to different **books related to mythology** in English
        - When I have time, I dive into any **Action/RPG** game with open world
        - One of the reasons I like being a developer is that I will be able to work remotely and **travel** all the time (hopefully)

# Footer
footer_show_references: true
references_title: | 
  Telegram: <a>https://t.me/ElizavG</a>

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
